### ISSUE TITLE
Sidebar is a mess on the 'add section' part of the survey builder

### ISSUE THREAD

**Issue by simonrolph** [simonrolph/NatureCounts#53]
![image](https://user-images.githubusercontent.com/17750766/115705234-35d2da00-a364-11eb-9540-5aadc08fe91b.png)

**Comment by simonrolph** [comment]
tracked it down to this piece of css:
![image](https://user-images.githubusercontent.com/17750766/115731546-2319ce80-a37f-11eb-806b-6df71def14de.png) which unticking it seems to fix it

Also some of the symbols are a bit wrong:
![image](https://user-images.githubusercontent.com/17750766/115731885-683e0080-a37f-11eb-93c6-c5b3c213160a.png)

**Comment by johnvanbreda** [comment]
Does adding 
```css
#drupal-off-canvas .layout-selection div {
  all: inherit;
}
```
help? I found this in my notes from another project. Also see https://www.drupal.org/project/bootstrap_layouts/issues/2949262

**Comment by johnvanbreda** [comment]
Fixed by addition of the following:
```scss
/** Bootstrap Layouts fix **/
#drupal-off-canvas {
  select {
    -webkit-appearance: none;
    -moz-appearance: none;
  }
  select[multiple] {
    padding: 0;
    overflow: scroll;
    min-height: 220px;
    width: 100%;
  }
  .layout-selection div {
    all: inherit;
  }
  .button, button {
    border: solid silver 1px;
    border-radius: 8px;
    padding: 4px;
    margin: 8px;
    display: inline-block;
    vertical-align: middle;
  }
}
```
